apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: streamlit
  name: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  strategy: {}
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - image: jahidshaik/udemy-streamlit:latest
        name: udemy-streamlit
        ports:
        - containerPort: 8501
        resources: {}
status: {}
